apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-deployment
  name: app-svc
  namespace: app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: app-deployment
  type: NodePort
status:
  loadBalancer: {}
