apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-psql-deploy
  name: db-svc
  namespace: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: db-psql-deploy